/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Vista.tabla.tabla;
import Controlador.ControladorListaMulta;
import Controlador.Utilidades;
import Modelo.MultasTransito;
import Vista.utilidades.UtilidadesComponentes;
import java.awt.event.ItemEvent;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author ASUS
 */
public class Frm_Multas extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Multas
     */
    ControladorListaMulta lista = new ControladorListaMulta();
    Utilidades utilidades = new Utilidades();
    UtilidadesComponentes utilidadesComponentes = new UtilidadesComponentes();
    tabla modelo = new tabla();
    public Frm_Multas() {
        initComponents();
        lista.leerTxt();
        cargarTextoLabel();
        cargarTabla();
        cargarDatos();
    }
    
    public void cargarTabla(){
        modelo.setLista(lista.getLista());
        tablaMultas.setModel(modelo);
        modelo.ajustarTabla(tablaMultas);
        tablaMultas.updateUI();
    }
    
    public void cargarTextoLabel(){
        txtAreaPorcentajeMulta.setEditable(false);
        //txtAreaPorcentajeMulta.setOpaque(true);
        txtAreaPorcentajeMulta.setText(utilidades.leerTxtProcetajeMulta());
    }
    
    public void cargarDatos(){
        utilidadesComponentes.cargarCombo(cbxRubro);
        AutoCompleteDecorator.decorate(cbxRubro);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaMultas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaPorcentajeMulta = new javax.swing.JTextArea();
        cbxRubro = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAreaDescripcion = new javax.swing.JTextArea();
        txtTipo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tablaMultas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        tablaMultas.setRowHeight(30);
        jScrollPane1.setViewportView(tablaMultas);

        txtAreaPorcentajeMulta.setColumns(20);
        txtAreaPorcentajeMulta.setRows(5);
        jScrollPane2.setViewportView(txtAreaPorcentajeMulta);

        cbxRubro.setEditable(true);
        cbxRubro.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxRubroItemStateChanged(evt);
            }
        });
        cbxRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxRubroActionPerformed(evt);
            }
        });
        cbxRubro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbxRubroKeyPressed(evt);
            }
        });

        txtAreaDescripcion.setColumns(20);
        txtAreaDescripcion.setRows(5);
        jScrollPane3.setViewportView(txtAreaDescripcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxRubro, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(cbxRubro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxRubroActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxRubroActionPerformed

    private void cbxRubroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbxRubroKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cbxRubroKeyPressed

    private void cbxRubroItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxRubroItemStateChanged
        // TODO add your handling code here:
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            try {
                String s = cbxRubro.getSelectedItem().toString();
                System.out.println(s);
                MultasTransito dato = lista.getLista().obtenerPorPosicion(cbxRubro.getSelectedIndex());
                System.out.println(cbxRubro.getSelectedIndex());
                txtAreaDescripcion.setText(dato.getDescripcion());
                txtTipo.setText(dato.getTipoFalta());
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_cbxRubroItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Multas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Multas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Multas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Multas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Multas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxRubro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tablaMultas;
    private javax.swing.JTextArea txtAreaDescripcion;
    private javax.swing.JTextArea txtAreaPorcentajeMulta;
    private javax.swing.JTextField txtTipo;
    // End of variables declaration//GEN-END:variables
}
